### PR TITLE
Nested

### LINKED ISSUE #285: managing columns in a non-collapseable column
see also #219 

Max/Mean/Min/Scripted are all composite column. However, they don't show their children directly but just the aggregate. While columns can be added using dnd (#284) you can't tell which columns exist and have no way to remove them.

### PR DESCRIPTION
**Pull request by sgratzl**
closes #285 

2017-10-17 15_52_50-lineup alpha

### CODE REVIEW

**Comment by mstreit** [comment]
very nice and important for the paper that we can address the nesting requirement.

**Comment by mstreit** [comment]
Why are there three blocks shown for C in your screenshot?

**Comment by sgratzl** [comment]
> Why are there three blocks shown for C in your screenshot?

it is a histogram but just for 4 rows in total

**Comment by thinkh** [comment]
Works as expected.

**Pull request merged**
