### PR TITLE
Add check for arrays in isMissingValue()

### LINKED ISSUE #369: Add missing value encoding to matrix boxplot renderer
image

Add missing value encoding (similar to numerical column) if no boxplot can be shown.

### PR DESCRIPTION
**Pull request by thinkh**
Closes #369.

Drawing the missing value encoding for the boxplot was already implemented. I've added the check for Arrays to the `isMissingValue()` check.

image

### CODE REVIEW

**Comment by sgratzl** [comment]
do we really want if a single value in the array is missing that the whole boxplot is not shown?

**Comment by mstreit** [comment]
I agree that box plots should be shown if the majority of values is present. The question is how the 'majority' should be defined.

In the heatmap mode the single missing values could be indicated per cell.

**Comment by thinkh** [comment]
> The question is how the 'majority' should be defined.
More than 75%?

We could also make the color brighter/transparent if there missing values.

**Comment by sgratzl** [comment]
@mstreit so what is the percentage to consider a row as missing if individual items are missing

**Comment by sgratzl** [comment]
100% missing items -> missing row

**Comment by thinkh** [comment]
Last commit changes it to 100%.

Artificial change shows that the heatmap is still rendered even when there are 2 values missing:

image

Same for box plot:

image

**Pull request merged**
