### PR TITLE
hides the header toolbar when taggle is in context mode

### PR DESCRIPTION
**Pull request by lehnerchristian**
Closes https://github.com/Caleydo/tdp_bi_bioinfodb/issues/788

### CODE REVIEW

**Comment by mstreit** [comment]
@think, can you merge this please? AFAIK that's the only issue that is preventing us from recording the video.

**Comment by thinkh** [comment]
@lehnerchristian It works for me in general, but I can still use the resize handle of hidden columns; did you do it intentionally like this?

image

**Comment by lehnerchristian** [comment]
no, I didn't do that at all, @thinkh ;-)
I don't know much how columns in Taggle are hidden, I just thought that the overflow-x is missing, since the description is hidden using the same way (as far as I could see)
but I currently don't know how to hide the handle to be honest

**Comment by thinkh** [comment]
I think it's ok for now. I'll merge it. For later we should think of a cleaner solution.

**Pull request merged**
