### PR TITLE
Feature d3 v4

### PR DESCRIPTION
**Pull request by sgratzl**
related issues:  #141

### Pre merge/review checklist
* [ ] branch is up-to-date with the branch to be merged with, i.e. master
* [ ] travis build works
* [ ] internal code review by requester is done:
  * [ ] code is formatted
  * [ ] removed debug output `console.log`, ...
  * [ ] use of `const` whenever possible otherwise `let` to declare variables
  * [ ] use of `readonly` for readonly fields and interfaces fields
  * [ ] parameters, fields, variables that are not initialized are typed, e.g.,  `function f(a)` => `function f(a: number)` 
  * [ ] optional options objects are typed using option interfaces, see e.g. `ILineUpConfig`
  * [ ] code is formatted using your preferred editor formatting tool (e.g. atom beautifier, WebStorm Format Code,...)
  * [ ] use of meaningful names in camelCase especially for public functions and fields
  * [ ] file structure: avoid of large code files containing multiple elements (classes, functions) better to create a nested structure, e.g., `model`
  * [ ] in case of DOM elements: assigning the `id` is avoided or the prefix in the lineup config is prepended
  * [ ] in case of css styles: global classes prepended with `lu-` or within a `lu-` namespace
  * [ ] public fields/function those purpose is not obvious are documented
  * [ ] complex code is documented
  * [ ] code is well structured regarding use of variable names, complexity
  * [ ] public interfaces (e.g. public interface of a class) are minimal, no superfluous fields, functions
  * [ ] complex code is not duplicated. Otherwise justified within the code, why needed
 * [ ] code reviewer is assigned
 * [ ] in case of second review round: review comments are justified or implemented

### CODE REVIEW

**Comment by thinkh** [comment]
@sgratzl Is this PR ready to merge or are you working on it?

**Comment by sgratzl** [comment]
> @sgratzl Is this PR ready to merge or are you working on it?

lineup is migrated to v4 and sync with latest release 1.x branch. However, the main question is: Do we want to merge it now?

I don't know about side effects. especially if you are using the source code and not the build as e.g. phovea, does

**Comment by timelyportfolio** [comment]
any updates here? I might have a good use for lineup in a project I am working on.  Thanks for the brilliant work!

**Comment by sgratzl** [comment]
> any updates here? I might have a good use for lineup in a project I am working on. Thanks for the brilliant work!

Hi, we are currently not sure, when we switch to D3 v4, since we use LineUp in a couple of other projects that still run using d3 v3. 

However, I will update this branch, such that you could use this specific d3 v4 branch.

**Comment by timelyportfolio** [comment]
wow, thanks!!!

**Pull request closed without merging**
