### PR TITLE
Refactor overview button style

### PR DESCRIPTION
**Pull request by thinkh**
Closes Caleydo/lineupjs#413

image

### CODE REVIEW

**Comment by thinkh** [comment]
Updated tooltip text:

image

**Comment by sgratzl** [comment]
image

desired behavior?

**Comment by thinkh** [comment]
@sgratzl 
How did you get to this state?

**Comment by sgratzl** [comment]
> @sgratzl How did you get this state?

filter out all but 10 rows. As far as I can see you removed the condition checking for a maximal height of an item

**Pull request merged**
